# Set the version of docker compose to use
version: "3.8"

# The containers that compose the project
services:
  db:
    image: postgres:latest
    restart: always
    container_name: integration-tests-prisma
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
